version: "3"

services:
  signal-cli-rest-api:
    image: bbernhard/signal-cli-rest-api:0.53
    environment:
      - MODE=json-rpc
      - PORT=8080
    ports:
      - "8080:8080"
    volumes:
      - "./signal-cli-config:/home/.local/share/signal-cli"
