name: Deploy Pull Request

on:
  pull_request:
    branches: [master]

jobs:
  # run-tests:
  #   name: Run Tests
  #   uses: filipre/renebot-signal/.github/workflows/run-tests.yml@master

  publish-package:
    name: Publish Pull Request
    runs-on: ubuntu-latest
    environment:
      name: test.pypi.org
      url: https://test.pypi.org/project/signalbot
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.13
      - name: Install dependencies
        run: poetry install --no-dev
      - name: Print some basic stats
        run: |
          echo ${{ github.run_attempt }}
      - name: Create custom version
        run: |
          pr_version=$(poetry version -s)a${{ github.run_attempt }}
          poetry version $pr_version
      - name: Confirm new version
        run: poetry version
      - name: Build package
        run: poetry build
      - name: Add test.pypi.org to Poetry
        run: |
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          poetry config pypi-token.testpypi ${{ secrets.API_TOKEN }}
      - name: Publish package
        run: poetry publish -r testpypi
